packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - argon2
  - prisma
  - esbuild
  - msgpackr-extract
