packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  msgpackr-extract: set this to true or false

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - argon2
  - prisma
  - esbuild
  - msgpackr-extract
